[package]
name = "webdav-server-rs"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

[workspace]

[dependencies]
bytes = "0.4.11"
clap = "2.32.0"
env_logger = "0.6.0"
fs_quota = { path = "fs_quota" }
futures = "0.1.25"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.13", features = ["io-compat"] }
http = "0.1.14"
hyper = "0.12.20"
lazy_static = "1.2.0"
libc = "0.2.47"
log = "0.4.6"
percent-encoding = "1.0.1"
regex = "1.1.0"
time = "0.1.42"
tokio = "0.1.14"
tokio-pam = { path = "pam" }
tokio-threadpool = "0.1.10"
url = "1.7.2"
webdav-handler = { path = "../webdav-handler-rs", version = "0.1.0" }
