[package]
name = "webdav-server-rs"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

[workspace]

[dependencies]
hyper = "0.12.20"
log = "0.4.6"
env_logger = "0.6.0"
url = "1.7.2"
regex = "1.1.0"
libc = "0.2.47"
time = "0.1.42"
lazy_static = "1.2.0"
clap = "2.32.0"
percent-encoding = "1.0.1"
tokio-pam = { path = "pam" }
fs_quota = { path = "fs_quota" }
webdav-handler = { path = "../webdav-handler-rs", version = "0.1.0" }
http = "0.1.14"
futures = "0.1.25"
bytes = "0.4.11"
tokio-threadpool = "0.1.10"
tokio = "0.1.14"
