[package]
name = "webdav-server"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"
license = "Apache-2.0"

[workspace]

[dependencies]
bytes = "0.4.12"
clap = "2.32.0"
env_logger = "0.6.1"
fs-quota = { path = "fs_quota", version = "0.1.0" }
futures = "0.1.25"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.13", features = ["io-compat"] }
http = "0.1.16"
hyper = "0.12.25"
lazy_static = "1.3.0"
libc = "0.2.50"
log = "0.4.6"
pam-sandboxed = { path = "pam", version = "0.1.0" }
percent-encoding = "1.0.1"
regex = "1.1.2"
time = "0.1.42"
tokio = "0.1.16"
tokio-threadpool = "0.1.12"
url = "1.7.2"
webdav-handler = { path = "../webdav-handler-rs", version = "0.1.0" }
serde_derive = "1.0.89"
serde = "1.0.89"
toml = "0.4.10"
net2 = "0.2.33"
