[package]
name = "webdav-server"

# When releasing to crates.io:
# - Update html_root_url in src/main.rs
# - Update CHANGELOG.md.
# - Create git tag webdav-server-0.x.y
version = "0.1.0"

readme = "README.md"
documentation = "https://docs.rs/webdav-server"
repository = "https://github.com/miquels/webdav-server-rs"
homepage = "https://github.com/miquels/webdav-server-rs"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"
license = "Apache-2.0"
categories = ["filesystem"]

[workspace]

[dependencies]
bytes = "0.4.12"
clap = "2.33.0"
env_logger = "0.6.1"
fs-quota = { path = "fs_quota", version = "0.1.0" }
futures = "0.1.26"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.15", features = ["io-compat"] }
http = "0.1.17"
hyper = "0.12.28"
lazy_static = "1.3.0"
libc = "0.2.53"
log = "0.4.6"
pam-sandboxed = { path = "pam", version = "0.1.0" }
percent-encoding = "1.0.1"
regex = "1.1.6"
time = "0.1.42"
tokio = "0.1.19"
tokio-threadpool = "0.1.14"
url = "1.7.2"
webdav-handler = { path = "../webdav-handler-rs", version = "0.1.0" }
serde_derive = "1.0.90"
serde = "1.0.90"
toml = "0.5.0"
net2 = "0.2.33"
serde_json = "1.0.39"
handlebars = "1.1.0"
headers = "0.2.1"

[dev-dependencies]
# temp, see https://github.com/tokio-rs/tokio/issues/1056
#tokio-sync = "0.1.5"

