#
# server settings.
#
[server]
  # HTTP Port(s) to listen on.
  # (https not implemented yet - use a frontend proxy like nginx)
  listen = [ "0.0.0.0:4918", "[::]:4918" ]
  # Unix uid/gid to run under (when not running setuid as user).
  uid = 33
  gid = 33

#
# user settings.
#
[accounts]
  # which accounts are defined.
  acct-type = "unix"
  # how to authenticate.
  auth-type = "pam"
  # do we run setuid if authenticated.
  setuid = true

#
# webdav protocol settings.
#
[webdav]
  # locking can be "none" (default) or "fake". Fake locking is only
  # advertized to Windows and OSX clients.
  locking = "fake"

#
# PAM authentication settings.
#
[pam]
  # PAM service to use.
  service = "webdav"
  # Maximum time to cache between requests (secs).
  cache-timeout-between = 120
  # Absolute maximum cache time (secs)
  cache-timeout-absolute = 600
  # Number of thread to use for the PAM service threadpool.
  threads = 8

#
# Unix account settings.
#
[unix]
  # Cache timeout (secs). 0 disables the cache.
  cache-timeout = 60
  # UIDs under this value cannot login.
  min-uid = 1000

#
# Root filesystem.
#
# This serves an index.html to GET/HEAD "/" requests from browsers.
# It also serves any other files present in the directory.
#
# If "auth" is set, clients must login to see the content.
#
# If "webdav"  is set, then:
# - all methods other than GET will force authentication
# - OPTIONS / will return a reasonable result
# - PROPFIND / will return one entry, for "/username/" (the clients username)
# - all other methods will return a 405 status code.
#
[rootfs]
  # Path. Usually "/", but it doesn't have to be.
  path = "/"
  # Directory to serve.
  directory = "/var/www/html"
  # Index file.
  index = "index.html"
  # Force authentication even for simple GET/HEAD requests
  auth = true
  # Enable PROPFIND and OPTIONS for webdav clients (authenticated)
  webdav = true

#
# Users.
#
# To access this part of the server namespace, the client must be
# authenticated. Then full read/write access is allowed in the
# clients directory on files owned by the uid/gid the server is
# running under - if accounts.setuid is true, that is the users
# uid/gid, otherwise it's the global server uid/gid.
#
[users]
  # Path. If this contains ":username", then that part of the path
  # must match the username. Most common setting here is "/:username".
  path = "/:username"
  # Do we serve GET requests on directories as a HTML index (default true)
  dirindex = true

