#
# Webdav server settings.
#
[server]
  # HTTP Port(s) to listen on.
  # (https not implemented yet - use a frontend proxy like nginx)
  listen = [ "0.0.0.0:4918", "[::]:4918" ]
  # Unix uid/gid to run under (when not running setuid as user).
  # Optional - if not set, will not change uid.
  uid = 33
  gid = 33

#
# User settings.
#
[accounts]
  # which accounts are defined.
  acct-type = "unix"
  # how to authenticate.
  auth-type = "pam"
  # do we run setuid if authenticated (default: false).
  setuid = true
  # realm to use with basic authentication (default: "Webdav Server").
  realm = "Webdav Server"

#
# Webdav protocol settings.
#
[webdav]
  # locksystem can be "fakels" (default) or "none". Fake locking is only
  # advertized to Windows and OSX clients (based on User-Agent header).
  locksystem = "fakels"

#
# PAM authentication settings.
#
[pam]
  # PAM service to use.
  service = "webdav"
  # Cache timeout (secs). 0 disables the cache (default: 120).
  cache-timeout = 120
  # Number of thread to use for the PAM service threadpool (default: 8).
  threads = 8

#
# Unix account settings.
#
[unix]
  # Cache timeout (secs). 0 disables the cache (default: 120).
  cache-timeout = 120
  # UIDs under this value cannot login (default: 0).
  min-uid = 1000

#
# Root filesystem.
#
# This serves an index.html to GET/HEAD "/" requests from browsers.
# It also serves any other files present in the directory.
#
# If "auth" is set, browser clients must authenticate to see the content.
#
[rootfs]
  # URL path to this directory.
  path = "/"
  # Directory to serve.
  directory = "/var/www/html"
  # Index file (default: "index.html").
  index = "index.html"
  # Client must authenticate (default: false).
  auth = false

#
# Users.
#
# To access this part of the server namespace, the client must be
# authenticated. Then full read/write access is allowed in the
# clients directory on files owned by the uid/gid the server is
# running under - if accounts.setuid is true, that is the users
# uid/gid, otherwise it's the global server uid/gid.
#
[users]
  # Path. If this contains ":username", then that part of the path
  # must match the username. Most common setting here is "/:username".
  # In that case, a request for the path _without_ ":username" will
  # result in a virtual directory containing 1 item, the username
  # sent by the client.
  path = "/:username"

