[package]
name = "fs-quota"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
license = "Apache-2.0"

[build-dependencies]
cc = "1.0.29"

[dependencies]
libc = "0.2.49"
log = "0.4.6"
