[package]
name = "pam"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]

[build-dependencies]
cc = "1"

[dependencies]
lazy_static = "1"
bincode = "1.0.0"
libc = "0.2.36"
log = "0.3"
serde = "1.0.27"
serde_derive = "1.0.27"
error-chain = "0.11"
unix_socket = "0.5"
