[package]
name = "pam-sandboxed"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"
license = "Apache-2.0"

[build-dependencies]
cc = "1.0.35"

[dependencies]
bincode = "1.1.3"
env_logger = "0.6.1"
error-chain = "0.12.0"
futures = "0.1.26"
libc = "0.2.51"
log = "0.4.6"
serde = "1.0.90"
serde_derive = "1.0.90"
threadpool = "1.7.1"
tokio = "0.1.18"
tokio-core = "0.1.17"
tokio-io = "0.1.12"
tokio-reactor = "0.1.9"
tokio-uds = "0.2.5"
